-- 删除Oracle特有的序列语法和注释声明
CREATE TABLE sys_log (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
  username VARCHAR(50) DEFAULT NULL COMMENT '用户名',
  operation VARCHAR(50) DEFAULT NULL COMMENT '用户操作',
  time INT DEFAULT NULL COMMENT '响应时间（毫秒）',
  method VARCHAR(200) DEFAULT NULL COMMENT '请求方法',
  params VARCHAR(500) DEFAULT NULL COMMENT '请求参数',
  ip VARCHAR(64) DEFAULT NULL COMMENT 'IP地址',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
ALTER TABLE sys_log ADD INDEX idx_create_time (create_time);
ALTER TABLE sys_log ADD INDEX idx_username (username);
